using System;
using System.Collections.Generic;
using System.Text;

namespace AwsCloudNative.Data.Entities
{
    /// <summary>
    /// Represents a persisted order record in the PostgreSQL Orders database.
    /// WHY sealed: Entity classes should not be subclassed — EF Core
    /// proxy generation works correctly with sealed classes in most scenarios
    /// and sealing prevents accidental inheritance misuse.
    ///
    /// Naming convention: suffix "Entity" distinguishes database entities
    /// from domain models and API DTOs (Data Transfer Objects).
    /// This prevents accidental coupling between the persistence and API layers.
    /// </summary>
    public sealed class OrderEntity
    {
        /// <summary>
        /// Primary key — UUID generated by the application, not the database.
        /// WHY application-generated UUID over database serial:
        /// Application-generated IDs allow the entity to be created and used
        /// in memory before the database round-trip completes.
        /// Avoids a SELECT after INSERT to retrieve the generated ID.
        /// Also safe for distributed insert scenarios.
        /// </summary>
        public Guid Id { get; set; }

        /// <summary>
        /// Business-level order identifier used externally.
        /// Separate from the database PK (Primary Key) — the PK is internal.
        /// Indexed for fast lookup by OrderId without exposing the PK.
        /// </summary>
        public string OrderId { get; set; } = string.Empty;

        /// <summary>Customer identifier from the Cognito sub claim.</summary>
        public string CustomerId { get; set; } = string.Empty;

        /// <summary>Order total in the account's base currency.</summary>
        public decimal Amount { get; set; }

        /// <summary>
        /// Current order status.
        /// Stored as a string (not int) for readability in the database
        /// and to avoid enum-to-int mapping confusion during migrations.
        /// </summary>
        public string Status { get; set; } = OrderStatus.Pending;

        /// <summary>UTC (Coordinated Universal Time) timestamp when the order was created.</summary>
        public DateTime CreatedAtUtc { get; set; }

        /// <summary>
        /// UTC timestamp of the last status update.
        /// WHY nullable: Set only when the order is updated after creation.
        /// </summary>
        public DateTime? UpdatedAtUtc { get; set; }

        /// <summary>
        /// EF Core concurrency token.
        /// WHY: Prevents lost-update race conditions when two processes
        /// update the same order simultaneously.
        /// EF Core includes this value in UPDATE WHERE clauses automatically.
        /// If the row was modified between read and write, the update affects
        /// 0 rows → EF Core throws DbUpdateConcurrencyException.
        /// </summary>
        public uint RowVersion { get; set; }
    }

    /// <summary>
    /// Valid order status values stored in OrderEntity.Status.
    /// WHY constants over enum: Stored as strings in PostgreSQL.
    /// Avoids enum-to-integer mapping issues in EF Core migrations
    /// and makes the database rows human-readable without a lookup.
    /// </summary>
    public static class OrderStatus
    {
        public const string Pending = "Pending";
        public const string Processing = "Processing";
        public const string Completed = "Completed";
        public const string Failed = "Failed";
        public const string Cancelled = "Cancelled";
    }
}
